name: date_checker_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  floor: ^0.12.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.1
  flutter_typeahead: ^1.8.0
  cupertino_icons: ^0.1.2
  http: ^0.12.1
  get_it: ^4.0.2
  getflutter: ^1.0.11
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  floor_generator: ^0.12.0
  build_runner: ^1.7.3
  bloc_test: ^3.0.0
  sqflite_ffi_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_ffi_test
flutter:
  uses-material-design: true

