name: date_checker_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  floor: ^0.9.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  flutter_typeahead: ^1.8.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.9.0
  build_runner: ^1.7.1
  bloc_test: ^3.0.0
flutter:
  uses-material-design: true

